// React/bible-verse-tracker/src/components/BibleVerseDelete.js
import React, { useEffect, useState } from 'react';
import { getAllVerses, deleteVerse } from '../services/bibleVerseService';

function BibleVerseDelete() {
  const [verses, setVerses] = useState([]);
  const [error, setError] = useState('');

  useEffect(() => {
    fetchBibleVerses();
  }, []);

  const fetchBibleVerses = async () => {
    try {
      const response = await getAllVerses();
      setVerses(response.data);
    } catch (err) {
      setError('Failed to load Bible verses.');
    }
  };

  const handleDelete = async (verseId) => {
    const confirmation = window.confirm(
      'Are you sure you want to delete this verse?'
    );
    if (confirmation) {
      try {
        await deleteVerse(verseId);
        fetchBibleVerses();
      } catch (err) {
        alert('Failed to delete Bible verse.');
      }
    }
  };

  return (
    <div>
      <h2>Delete a Bible Verse</h2>
      {error && <div className="alert alert-danger">{error}</div>}
      <ul>
        {verses.map((verse) => (
          <li key={verse.verseId}>
            {verse.book} {verse.chapter}:{verse.verseNumber}
            <button onClick={() => handleDelete(verse.verseId)}>Delete</button>
          </li>
        ))}
      </ul>
    </div>
  );
}

export default BibleVerseDelete;

// BibleVerseTracker/src/app/bible-verse-delete/bible-verse-delete.component.ts
import { Component, OnInit } from '@angular/core';
import { BibleVerseService } from '../service/bible-verse.service'; 

@Component({
  selector: 'app-bible-verse-delete',
  standalone: false,
  templateUrl: './bible-verse-delete.component.html',
  styleUrls: ['./bible-verse-delete.component.scss']
})
export class BibleVerseDeleteComponent implements OnInit {
  verses: any[] = [];  // To store the list of verses from the database
  selectedVerseId: number | null = null;  // To store the id of the selected verse
  errorMessage: string | null = null; // To store error message if any occurs during the API call

  constructor(private bibleVerseService: BibleVerseService) {}

  ngOnInit(): void {
    this.loadBibleVerses();  // Load the Bible verses on component init
  }

  // Load all Bible verses
  loadBibleVerses(): void {
    this.bibleVerseService.getAllVerses().subscribe(
      (data) => {
        this.verses = data;
        this.errorMessage = null; // Reset error message if the load is successful
      },
      (error) => {
        this.errorMessage = 'Failed to load Bible verses. Please try again later.';
        console.error('Error loading Bible verses:', error);
      }
    );
  }

  // Handle delete request with confirmation
  deleteBibleVerse(): void {
    if (this.selectedVerseId) {
      const confirmation = confirm('Are you sure you want to delete this verse?');
      if (confirmation) {
        this.bibleVerseService.deleteVerse(this.selectedVerseId).subscribe(
          () => {
            this.loadBibleVerses();  // Reload the verses after deletion
            this.selectedVerseId = null;  // Deselect the verse after deletion
            this.errorMessage = null; // Reset error message on successful deletion
          },
          (error) => {
            this.errorMessage = 'Failed to delete the Bible verse. Please try again later.';
            console.error('Error deleting Bible verse:', error);
          }
        );
      }
    }
  }

  // Handle selection of a verse
  selectVerse(verseId: number): void {
    this.selectedVerseId = verseId;
  }
}

<div class="container">
  <h3>Delete a Bible Verse</h3>

  <!-- Display error message if any -->
  <div *ngIf="errorMessage" class="alert alert-danger">
    {{ errorMessage }}
  </div>

  <!-- List of Bible Verses -->
  <ul class="list-group">
    <li *ngFor="let verse of verses" class="list-group-item">
      <span (click)="selectVerse(verse.verseId)" 
            [ngClass]="{'selected': verse.verseId === selectedVerseId}">
        {{ verse.book }} {{ verse.chapter }}:{{ verse.verseNumber }} - {{ verse.verseText }}
      </span>
    </li>
  </ul>

  <!-- Delete Button -->
  <button class="btn btn-danger" (click)="deleteBibleVerse()" 
          [disabled]="!selectedVerseId">Delete</button>
</div>
