// React/bible-verse-tracker/src/components/BibleVerseCreate.js
import React, { useState } from 'react';
import { createVerse } from '../services/bibleVerseService';

function BibleVerseCreate() {
  const [formData, setFormData] = useState({
    book: '',
    chapter: '',
    verseNumber: '',
    verseText: '',
    dateAdded: new Date().toISOString(),
  });

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData({ ...formData, [name]: value });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      await createVerse(formData);
      alert('Bible verse created successfully!');
      setFormData({
        book: '',
        chapter: '',
        verseNumber: '',
        verseText: '',
        dateAdded: new Date().toISOString(),
      }); // Reset form
    } catch (err) {
      alert('Failed to create Bible verse.');
    }
  };

  return (
    <div className="container">
      <h2>Add A New Bible Verse</h2>
      <form onSubmit={handleSubmit}>
        <div className="form-group">
          <label htmlFor="book">Book</label>
          <input
            type="text"
            className="form-control"
            id="book"
            name="book"
            value={formData.book}
            onChange={handleChange}
            required
          />
        </div>
        <div className="form-group">
          <label htmlFor="chapter">Chapter</label>
          <input
            type="number"
            className="form-control"
            id="chapter"
            name="chapter"
            value={formData.chapter}
            onChange={handleChange}
            required
          />
        </div>
        <div className="form-group">
          <label htmlFor="verseNumber">Verse</label>
          <input
            type="number"
            className="form-control"
            id="verseNumber"
            name="verseNumber"
            value={formData.verseNumber}
            onChange={handleChange}
            required
          />
        </div>
        <div className="form-group">
          <label htmlFor="verseText">Verse Text</label>
          <textarea
            className="form-control"
            id="verseText"
            name="verseText"
            value={formData.verseText}
            onChange={handleChange}
            required
          ></textarea>
        </div>
        <button type="submit" className="btn btn-primary mt-2">
          Create
        </button>
      </form>
    </div>
  );
}

export default BibleVerseCreate;

// BibleVerseTracker/src/app/bible-verse-create/bible-verse-create.component.ts
import { Component } from '@angular/core';
import { BibleVerseService } from '../service/bible-verse.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-bible-verse-create',
  standalone: false,
  templateUrl: './bible-verse-create.component.html',
  styleUrls: ['./bible-verse-create.component.scss']
})
export class BibleVerseCreateComponent {
  newVerse = {
    book: '',
    chapter: 0,
    verseNumber: 0,
    verseText: ''
  };

  constructor(private bibleVerseService: BibleVerseService, private router: Router) { }

  createVerse(): void {
    this.bibleVerseService.createVerse(this.newVerse).subscribe(() => {
      this.router.navigate(['/bible-verse-list']);
    });
  }
}

<div class="container">
    <h2>Create New Bible Verse</h2>
    <form (ngSubmit)="createVerse()">
      <div class="form-group">
        <label for="book">Book</label>
        <input type="text" class="form-control" id="book" [(ngModel)]="newVerse.book" name="book" required>
      </div>
      <div class="form-group">
        <label for="chapter">Chapter</label>
        <input type="number" class="form-control" id="chapter" [(ngModel)]="newVerse.chapter" name="chapter" required>
      </div>
      <div class="form-group">
        <label for="verseNumber">Verse</label>
        <input type="number" class="form-control" id="verseNumber" [(ngModel)]="newVerse.verseNumber" name="verseNumber" required>
      </div>
      <div class="form-group">
        <label for="verseText">Verse Text</label>
        <textarea class="form-control" id="verseText" [(ngModel)]="newVerse.verseText" name="verseText" required></textarea>
      </div>
      <button type="submit" class="btn btn-primary">Create</button>
    </form>
  </div>
