// React/bible-verse-tracker/src/components/BibleVerseList.js
import React, { useState, useEffect } from 'react';
import { getAllVerses, addToFavorites, deleteVerse } from '../services/bibleVerseService';
import { useNavigate } from 'react-router-dom';

function BibleVerseList() {
  const [verses, setVerses] = useState([]);
  const [error, setError] = useState('');
  const navigate = useNavigate();

  useEffect(() => {
    fetchBibleVerses();
  }, []);

  const fetchBibleVerses = async () => {
    try {
      const response = await getAllVerses();
      setVerses(response.data);
    } catch (err) {
      setError('Failed to load Bible verses. Please try again later.');
    }
  };

  const handleAddToFavorites = async (verse) => {
    try {
      await addToFavorites({ verseId: verse.verseId });
      alert('Verse added to favorites!');
    } catch (err) {
      alert('Failed to add verse to favorites.');
    }
  };

  const handleAddVerse = () => {
    navigate(`/create`); // Navigate to the add verse page
  };

  const handleEditVerse = (verseId) => {
    navigate(`/edit/${verseId}`); // Navigate to the edit page for the selected verse
  };

  const handleDeleteVerse = async (verseId) => {
    try {
      await deleteVerse(verseId);
      alert('Bible verse deleted successfully!');
      fetchBibleVerses(); // Refresh the list after deletion
    } catch (err) {
      alert('Failed to delete Bible verse.');
    }
  };

  return (
    <div className="container">
      <h2>Bible Verse List</h2>

      {/* Show error message if any */}
      {error && <div className="alert alert-danger">{error}</div>}

      {/* Show loading spinner while data is being fetched */}
      {verses.length === 0 && !error && (
        <div className="spinner-border" role="status">
          <span className="sr-only">Loading...</span>
        </div>
      )}

      {/* List of Bible Verses */}
      <ul className="list-group">
        {verses.map((verse) => (
          <li key={verse.verseId} className="list-group-item d-flex justify-content-between align-items-center">
            <span>
              {verse.book} {verse.chapter}:{verse.verseNumber} - {verse.verseText}
            </span>
            <div>
              <button
                className="btn btn-primary btn-sm me-2"
                onClick={() => handleEditVerse(verse.verseId)}
              >
                Edit
              </button>
              <button
                className="btn btn-danger btn-sm"
                onClick={() => handleDeleteVerse(verse.verseId)}
              >
                Delete
              </button>
            </div>
          </li>
        ))}
      </ul>
      <br />
      {/* Buttons for adding and deleting verses */}
      <div className="mb-3">
        <button className="btn btn-success me-2" onClick={handleAddVerse}>
          Add Bible Verse
        </button>
      </div>
    </div>
  );
}

export default BibleVerseList;

// Angular/BibleVerseTracker/src/app/bible-verse-list/bible-verse-list.component.ts
import { Component, OnInit } from '@angular/core';
import { BibleVerseService } from '../service/bible-verse.service';

@Component({
  selector: 'app-bible-verse-list',
  standalone: false,
  templateUrl: './bible-verse-list.component.html',
  styleUrls: ['./bible-verse-list.component.scss']
})
export class BibleVerseListComponent implements OnInit {
  verses: any[] = [];
  errorMessage: string | null = null;  // Store error message
  isLoading = true;  // Track loading state

  constructor(private bibleVerseService: BibleVerseService) { }

  ngOnInit(): void {
    this.loadBibleVerses();
  }

  // Load all Bible verses
  loadBibleVerses(): void {
    this.bibleVerseService.getAllVerses().subscribe(
      (data) => {
        this.verses = data;
        this.isLoading = false; // Set loading to false after data is loaded
        this.errorMessage = null; // Reset error message on successful load
      },
      (error) => {
        this.isLoading = false;
        this.errorMessage = 'Failed to load Bible verses. Please try again later.';
        console.error('Error loading Bible verses:', error);
      }
    );
  }

  // Delete a verse with confirmation
  deleteVerse(id: number): void {
    const confirmation = confirm('Are you sure you want to delete this verse?');
    if (confirmation) {
      this.bibleVerseService.deleteVerse(id).subscribe(
        () => {
          this.verses = this.verses.filter(verse => verse.id !== id);  // Remove deleted verse from the list
        },
        (error) => {
          this.errorMessage = 'Failed to delete the Bible verse. Please try again later.';
          console.error('Error deleting Bible verse:', error);
        }
      );
    }
  }
}

<div class="container">
    <h2>Bible Verse List</h2>
  
    <!-- Show error message if any -->
    <div *ngIf="errorMessage" class="alert alert-danger">
      {{ errorMessage }}
    </div>
  
    <!-- Show loading spinner while data is being fetched -->
    <div *ngIf="isLoading" class="spinner-border" role="status">
      <span class="sr-only">Loading...</span>
    </div>
  
    <!-- List of Bible Verses -->
    <ul class="list-group">
      <li *ngFor="let verse of verses" class="list-group-item">
        {{ verse.book }} {{ verse.chapter }}:{{ verse.verseNumber }} - {{ verse.verseText }}
      </li>
    </ul>
  </div>
