// React/bible-verse-tracker/src/components/BibleVerseDelete.js
import React, { useEffect, useState } from 'react';
import { getAllVerses, deleteVerse } from '../services/bibleVerseService';

function BibleVerseDelete() {
  const [verses, setVerses] = useState([]);
  const [error, setError] = useState('');

  useEffect(() => {
    fetchBibleVerses();
  }, []);

  const fetchBibleVerses = async () => {
    try {
      const response = await getAllVerses();
      setVerses(response.data);
    } catch (err) {
      setError('Failed to load Bible verses.');
    }
  };

  const handleDelete = async (verseId) => {
    const confirmation = window.confirm(
      'Are you sure you want to delete this verse?'
    );
    if (confirmation) {
      try {
        await deleteVerse(verseId);
        fetchBibleVerses();
      } catch (err) {
        alert('Failed to delete Bible verse.');
      }
    }
  };

  return (
    <div>
      <h2>Delete a Bible Verse</h2>
      {error && <div className="alert alert-danger">{error}</div>}
      <ul>
        {verses.map((verse) => (
          <li key={verse.verseId}>
            {verse.book} {verse.chapter}:{verse.verseNumber}
            <button onClick={() => handleDelete(verse.verseId)}>Delete</button>
          </li>
        ))}
      </ul>
    </div>
  );
}

export default BibleVerseDelete;

// Angular/BibleVerseTracker/src/app/bible-verse-delete/bible-verse-delete.component.ts
import { Component, OnInit } from '@angular/core';
import { BibleVerseService } from '../service/bible-verse.service';

@Component({
  selector: 'app-bible-verse-delete',
  templateUrl: './bible-verse-delete.component.html',
  styleUrls: ['./bible-verse-delete.component.scss']
})
export class BibleVerseDeleteComponent implements OnInit {
  verses: any[] = [];
  errorMessage: string | null = null;

  constructor(private bibleVerseService: BibleVerseService) {}

  ngOnInit(): void {
    this.loadBibleVerses();
  }

  // Load all Bible verses
  loadBibleVerses(): void {
    this.bibleVerseService.getAllVerses().subscribe(
      (data) => {
        this.verses = data;
      },
      (error) => {
        this.errorMessage = 'Failed to load Bible verses. Please try again later.';
        console.error('Error loading Bible verses:', error);
      }
    );
  }

  // Handle delete request with confirmation
  confirmDelete(verseId: number): void {
    const confirmation = confirm('Are you sure you want to delete this verse?');
    if (confirmation) {
      this.bibleVerseService.deleteVerse(verseId).subscribe(
        () => {
          this.verses = this.verses.filter(verse => verse.verseId !== verseId);
        },
        (error) => {
          this.errorMessage = 'Failed to delete the Bible verse. Please try again later.';
          console.error('Error deleting Bible verse:', error);
        }
      );
    }
  }
}

<div class="container">
  <h3>Delete a Bible Verse</h3>

  <!-- Error Message -->
  <div *ngIf="errorMessage" class="alert alert-danger">
    {{ errorMessage }}
  </div>

  <!-- Bible Verses List -->
  <ul class="list-group">
    <li *ngFor="let verse of verses" class="list-group-item d-flex justify-content-between align-items-center">
      <span>{{ verse.book }} {{ verse.chapter }}:{{ verse.verseNumber }} - {{ verse.verseText }}</span>
      <button class="btn btn-danger btn-sm" (click)="confirmDelete(verse.verseId)">Delete</button>
    </li>
  </ul>
</div>
